[package]
name = "ops"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
paladin-core = { workspace = true }
serde = { workspace = true }
evm_arithmetization = { workspace = true }
proof_gen = { workspace = true }
tracing = { workspace = true }
keccak-hash = { workspace = true }

common = { path = "../common" }

[features]
default = []
test_only = []
